### ISSUE TITLE
Default values of width and height are different from default values of the canvas element on the w3c document

### ISSUE THREAD

**Issue by ledsun** [gor181/react-chartjs-2#10]
The `react-chartjs-2` [set 200](https://github.com/gor181/react-chartjs-2/blob/master/src/Chart.js#L27) to width and height of the canvas by default.

[A W3C document](https://www.w3.org/TR/2013/NOTE-html5-author-20130528/the-canvas-element.html#the-canvas-element) define them 300 and 150 as default value.
> The width attribute defaults to 300, and the height attribute defaults to 150.

The Chart.js is not set width and height of the canvas by default.
As a result, the aspect ratio of the canvas is 2.
But the `react-chartjs-2` is set 1 to the aspect ratio of the canvas.

I am confused by this.

**Comment by gor181** [comment]
Hey @ledsun ,

Thanks for reporting, should be sorted now.
Appreciate your time.

Goran
