### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead

### ISSUE THREAD

**Issue by pangrr** [gor181/react-chartjs-2#123]
This is a warning for React 15.x
This will be an error since React 16.x
This is supposed to be an easy fix.
So please fix this ASAP.
Suspect file src/index.js.

**Comment by jerairrest** [comment]
We accept PRs :)

**Comment by pangrr** [comment]
What are PRs?

**Comment by jerairrest** [comment]
See https://github.com/gor181/react-chartjs-2/pull/130
