### ISSUE TITLE
Typescript error: import {Chart} from 'react-chartjs-2'

### ISSUE THREAD

**Issue by thr0n** [gor181/react-chartjs-2#131]
Hi,
I have got a working bar chart but now I would like to register a plugin using `Chart.pluginService.register().` As a first step, the readme file told me to do the following import: `import { Chart } from 'react-chartjs-2';`

But when I try to start my application I get the following Typescript error:

> error TS2305: Module (...) has no exported member 'Chart'.

Am I missing something? Any help will be much appreciated!

**Comment by lee1994522** [comment]
@thr0n I have met the same error.How did you solve with it?

**Comment by thr0n** [comment]
Unfortunately we did not solve it. Due to lack of time we had to choose a different charting lib.

**Comment by lee1994522** [comment]
@thr0n Thanks for reply.At last I use
`const Chart = require('react-chartjs-2').Chart;` to deal with it

**Comment by darewreck54** [comment]
@lee1994522  If you look at the type definition, it's actually missing Chart.

**Comment by altruisticsoftware** [comment]
Definition is still missing here...

**Comment by tolnai** [comment]
patch-package to the rescue! 

```diff --git a/node_modules/react-chartjs-2/index.d.ts b/node_modules/react-chartjs-2/index.d.ts
index 528b219..972184e 100644
--- a/node_modules/react-chartjs-2/index.d.ts
+++ b/node_modules/react-chartjs-2/index.d.ts
@@ -57,6 +57,8 @@ export class Polar extends ChartComponent<ChartComponentProps> {}
 
 export class Bubble extends ChartComponent<ChartComponentProps> {}
 
+export const Chart = chartjs.Chart;
+
 export var defaults: {
   global: chartjs.ChartOptions & chartjs.ChartFontOptions;
   [key: string]: any;
```

**Comment by datenreisender** [comment]
Since `Chart` is really just passed through from `chart.js`, I solved the same problem for me by replacing
```js
import { Chart } from 'react-chartjs-2';
```
with 
```js
import { Chart } from 'chart.js';
```
in my code.

**Comment by aldi** [comment]
Any update on this issue?
