### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by svenfraeys** [gor181/react-chartjs-2#132]
when using I get following error when creating the Doughnut graph.

bundle.js:4831 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by jerairrest** [comment]
Hey @svenfraeys 

I have a release candidate as a PR right now which should fix this issue. Stay tuned and I'm hoping to get that released soonish
