### ISSUE TITLE
Can not resolve chart.js

### ISSUE THREAD

**Issue by SergeyShablenko** [gor181/react-chartjs-2#134]
```
ERROR in ./~/react-chartjs-2/lib/index.js
Module not found: Error: Can't resolve 'chart.js' in 'node_modules/react-chartjs-2/lib'
```

**Comment by KayBeSee** [comment]
Did you ever figure this out? I am getting the same error.

**Comment by jerairrest** [comment]
chart.js is a peer dependancy. make sure you include a version in your package.json yourself

**Comment by javaProgrammer44** [comment]
Please add these two lines inside the angular.json file

"scripts": [
  "node_modules/chart.js/dist/Chart.js",
  "node_modules/hammerjs/hammer.min.js"
],

**Comment by mdmasumbillah** [comment]
I faced same problem. How solved this?

Failed to compile.
./node_modules/react-chartjs-2/es/index.js
Module not found: Can't resolve 'chart.js'

**Comment by mdmasumbillah** [comment]
@jerairrest If you know how to solve this. Please tell me.

**Comment by swordsreversed** [comment]
Don't install chartjs like I did! Make sure to: 
```
npm i chart.js
```

https://www.npmjs.com/package/chart.js?activeTab=readme

**Comment by MarlonX19** [comment]
In case you're facing the issue 

> Failed to compile.
./node_modules/react-chartjs-2/es/index.js
Module not found: Can't resolve 'chart.js'

In React I solved this by using **npm i chart.js**

Apparently even though it's referred on package.json you have to install it individually

**Comment by narenkarn786** [comment]
npm install --save chart.js
This worked for me.

**Comment by sagarkb** [comment]
I'm getting the same error in react and I have also done npm install --save chart.js but still not working

**Comment by aegiz** [comment]
Don't forget that too use the library in your react project you should import it this way:
`import { Pie } from "react-chartjs-2";`
And **not**
import { Pie } from "@reactchartjs/react-chart.js";
;-)

**Comment by BismaJ** [comment]
update npm to the latest version, then install chart.js again. if still not working then clear cache from Appdata roaming.

**Comment by JinalBhanushali0628** [comment]
just restart the server. that's worked for me

**Comment by themanthan9** [comment]
> just restart the server. that's worked for me

This not work.

**Comment by Radmehr-aghdam** [comment]
`npm i chart.js `NOT WORK

But

`yarn add chart.js` WORKED!


It's like `2*2=5` But `2+2=4`   :|

**Comment by linktoahmad** [comment]
if npm install chart.js gives error just do 
npm i chart.js --legacy-peer-deps
