### ISSUE TITLE
How to exclue momentJS in order to reduce bundle size?

### ISSUE THREAD

**Issue by ceylons** [gor181/react-chartjs-2#137]
Hi, i love this package because it makes it very easy to make reactive charts with react.

However, when i use this package i am not able to only include the chart.min.js. That should result in this package have a bundle size on nearly 400kb.

Are there any workaround for that right now :-) ?

**Comment by jerairrest** [comment]
momentJS is not a dependancy of this package. Could it be a different package you're including perhaps?

**Comment by ceylons** [comment]
Sry for the late reply :-)

It seams like this package depends on the complete ChartJS package which includes momentJS. I think ChartJS also includes a build without momentJS(https://github.com/chartjs/Chart.js/issues/1479).
