### ISSUE TITLE
Support Scatter charts

### ISSUE THREAD

**Issue by jithin1987** [gor181/react-chartjs-2#143]
First of all thanks for this amazing library. Would it be possible to add Scatter type charts to existing supported ones? http://www.chartjs.org/docs/latest/charts/scatter.html

**Comment by intrueder** [comment]
@jithin1987 
From docs,
> To use a scatter chart, data must be passed as objects containing X and Y properties

That's all you need.

**Comment by kumarharsh** [comment]
@intrueder yes, that makes sense. But while translating chartjs directly to react code, I was expecting this to work:

```js
import { Scatter } from 'react-chartjs-2';
```

Which would have been equivalent to what you write in vanilla js: `var scChart = Chart.Scatter(canvas, {...})`.

`Chart.Bar`, `Chart.Line`, etc are exposed, so why not `Chart.Scatter` too? Just to be clear, I don't have a big problem with using `Line` for scatter chart per se, but for clarity and equivalence with chartjs API, it might be a good to have...

**Comment by kumarharsh** [comment]
FYI, there are some more settings involved for rendering a proper scatter chart using line charts. Refer to the defaults in this PR: https://github.com/chartjs/Chart.js/pull/4381
