### ISSUE TITLE
using react-chartjs in the browser

### ISSUE THREAD

**Issue by varunagg45** [gor181/react-chartjs-2#148]
I apologize in advance for the question if it has already been answered or not applicable. I am in between a high priority project and planning to use this library which we have already used in the past with npm, I want to use this to a legacy project which does not use npm, but not sure if I can use it without package manager. 

If yes can someone point me to that resource?

**Comment by jerairrest** [comment]
there is a umd version available here. https://github.com/gor181/react-chartjs-2/tree/master/lib

Good luck!
