### ISSUE TITLE
Bug with charts with two or more datasets

### ISSUE THREAD

**Issue by kumarharsh** [gor181/react-chartjs-2#154]
Hi, I've discovered a serious bug with this library when trying to render two or more datasets in the same chart. When the chart is updated (on componentWillReceiveProps) - for example - while using a HTML tooltip, the first dataset of the chart is copied to all other datasets. This issue does not happen in the base chartjs library.

See this fiddle, and hover your mouse over the line:
https://jsfiddle.net/RedDevil/nk9zbvfp/

---

After much pain, I found the bug is actually due to this code:
https://github.com/gor181/react-chartjs-2/blob/459504b79ba1917745c98861ba646185a22975b6/src/index.js#L161
which copies `datasets` around without checking for their indices.

There, it can be seen that the library uses a [`datasetKeyProvider` prop](https://github.com/gor181/react-chartjs-2/blob/459504b79ba1917745c98861ba646185a22975b6/src/index.js#L167) which by default resorts to check the label of each dataset.

The solution I found was to set a 'label' explicitly for each dataset. **This is not documented**, and is not how the base chartjs library works (canvas & HTML tooltips render perfectly well with the base chartjs lib).

Perhaps a good way would be to index datasets by their `index` rather than `label` - one would not expect to pass `dataset.label` when they are not rendering labels. The chartjs tooltips also work this way - they consider `index` to be the `key` for the dataset.

**Comment by jinyanghuang** [comment]
I am still having the same issue
![image](https://user-images.githubusercontent.com/23371580/108893300-edef3b00-75de-11eb-8ed6-8defcd2acbe0.png)
One line will disappear after amount of time. How do I fix it?
