### ISSUE TITLE
Chart component is updated every time onElementsClick is installed

### ISSUE THREAD

**Issue by lutovich** [gor181/react-chartjs-2#16]
Hello,

Thanks a lot for this library, is is really useful!

I'm having a small problem with chart being updated every time parent's state changes.
It seems like `ChartComponent#shouldComponentUpdate()` method always returns `true` when props contain `onElementsClick` function.
This is probably caused by `deepEqual` expecting only arguments of type 'object':
`typeof objA !== 'object' || objA === null || typeof objB !== 'object' || objB === null`
and `typeof props.onElementsClick === 'function'`.

I'd be happy to provide a PR but want to discuss the solution:
 1. just add `onElementsClick` to the list of excluded properties in  `shouldComponentUpdate()`;
 2. make `shouldComponentUpdate()` compare only `props.data`, `props.legend`, `props.options`, `props.type` and remove code for exclusion entirely.

Please let me know what is best and if I can submit a PR.

**Comment by gor181** [comment]
hey @lutovich ,

Good eye there!
Thanks for reporting, and you are completely right! 😮 

The current approach is to add the properties which should be excluded to the list in `shouldComponentUpdate`.
I would go that way considering there is only 1 function which should be taken care of, maybe when we would have more functions we could take different approach.

Let me know whether you are going to PR it or I can add the fix by the end of this week. 

Thanks for reporting.
Its nice to know that the lib is useful 👍

**Comment by lutovich** [comment]
@gor181 I'll try to create a PR today.
