### ISSUE TITLE
Calling Ref from a parent component

### ISSUE THREAD

**Issue by EmirGluhbegovic** [gor181/react-chartjs-2#20]
Hey there,

The charts are working nicely. Only issue I am having is that I want to do
this.refs.chart.chart_instance.toBase64Image() in the parent component which hosts the child component being the graph. It seems this.refs.chart.chart_instance.toBase64Image() only works in the child component as I cannot access .chart_instance in the parent component when referring to the child.

Any help here would be much appreciated. It is possible that I am thinking about this incorrectly

**Comment by gor181** [comment]
Hey @EmirGluhbegovic ,

Can you make a fiddle or similar, would really help to narrow it 👍 

thanks

**Comment by EmirGluhbegovic** [comment]
In child component returns the base64

`class child extends React.Component{
componentDidMount() {
    var pieChart = this.refs.chart.chart_instance.toBase64Image();
  }
render() {
    const options = {
      responsive: true,
      tooltips: {
        mode: 'label'
      },
      animation : false,
      legend: {
        display: false
      }
    };
    const data = {
      labels: [
        'Red',
        'Green',
        'Yellow'
      ],
      datasets: [{
        data: [300, 50, 100],
        backgroundColor: [
          '#FF6384',
          '#36A2EB',
          '#FFCE56'
        ],
        hoverBackgroundColor: [
          '#FF6384',
          '#36A2EB',
          '#FFCE56'
        ]
      }]
    };
    return(
      <Pie ref='chart' data={data} options={options} />
    )
  }
}`

in Parent component
Cannot access .chart_instance
`
class Parent extend React.Component{
componentDidMount() {
    var pieChart = this.refs.lineChart.chart_instance.toBase64Image();
  }

render() {
    return(
        <div className="col-md-12 inner-col">
          <QuoteLineGraph ref='lineChart' />
        </div>
    )
  }

}
`

**Comment by EmirGluhbegovic** [comment]
that came out very badly :S

**Comment by EmirGluhbegovic** [comment]
Child Component:
Base64 string works

`class Child extends React.Component {`
    `componentDidMount() {`
       `    var pieChart = this.refs.chart.chart_instance.toBase64Image();`
        `console.log(pieChart);`
    `}`

`render() {`
   ` return(`
      `<Pie ref='chart' data={data} options={options} />`
    `)`
  `}`
`}`


Parent Component
Cannot access ._chart_instance

`class Parent extends React.Component {`
`componentDidMount() {`
       ` var pieChart = this.refs.chart.chart_instance.toBase64Image();`
        `console.log(pieChart);`
    `}`
`render() {`
   ` return(`
      `<Child ref='chart' data={data} options={options} />`
    `)`
  `}`
`}`

**Comment by EmirGluhbegovic** [comment]
I have a feeling there is a way to refer to the chart_instance in the parent that I am not aware off possibly?

**Comment by gor181** [comment]
So you have a deep structure. What I can see is that you get the reference in the Child `componentDidMount`.

Try to make the Child as:

```
class Child extends React.Component {
  componentDidMount() {
    this.chart = this.refs.chart.chart_instance;
  }

  render() {
    return(
      <Pie ref='chart' data={data} options={options} />
    )
  }
}
```

And the Parent as:

```
class Parent extends React.Component {
  componentDidMount() {
    var pieChart = this.refs.chart.toBase64Image();
    console.log(pieChart);
  }
  render() {
    return(
    <Child ref='chart' data={data} options={options} />
    )
  }
}
```

Let me know how it goes.

**Comment by EmirGluhbegovic** [comment]
@gor181  Tried exactly as you have said, getting an error 
this.refs.lineChart.toBase64Image is not a function. 
I made sure I have
import ChartsJS from 'react-chartjs-2';
in the parent also. Unless this.chart is still not providing access to the chart_instance ?

**Comment by gor181** [comment]
@EmirGluhbegovic Yes I did this blindly, please check corrected example.

**Comment by EmirGluhbegovic** [comment]
@gor181  Thanks Bro, that works perfectly now. Guess its my lack of React there so not a react-chartjs-2 issue. Thanks for the help again.

**Comment by gor181** [comment]
No problem, glad it's working. It's not your react, we people tend to overcomplicate sometimes 👍  🍺
