### ISSUE TITLE
showXLabels opstion dont work on line chart

### ISSUE THREAD

**Issue by lilwayne470** [gor181/react-chartjs-2#21]
Hello, im tryin to build a line chart, ihave too many xlabels il trying to hide it by step, i passed this options (see code below) but seem like it dont work. Did somebody have an idea.
Thanks.
 ```javascript
const Options = {responsive: true,showXLabels: 4}; 

<PanelChart title ="GRAPH WATTAGE">
            <Line data={data} height={100} options={Options} />
          </PanelChart>
```

**Comment by gor181** [comment]
Hi,

Haven't configured it in that way so far. But check http://www.chartjs.org/docs/#chart-configuration , there is `xLabels` property you can add to `data` property.

At least so it seems .

**Comment by lilwayne470** [comment]
Thanks a lot, by the way good job this component is really useful

**Comment by gor181** [comment]
Thanks  a lot @lilwayne470 ! Cuddos are going to contributors 👍
