### ISSUE TITLE
eslint import/named complains about your named exports

### ISSUE THREAD

**Issue by zeroasterisk** [gor181/react-chartjs-2#22]
``` js
import { Bar } from 'react-chartjs-2';
```

```
$ npm list react-chartjs-2
└── react-chartjs-2@1.2.4

$ eslint imports/modules/Stats/components/HeroLineBarChart.js

.../imports/modules/Stats/components/HeroLineBarChart.js
  9:10  error  Bar not found in 'react-chartjs-2'  import/named
```

I don't see any obvious problem, looking at your code, but thought you should know about this lint/import complaint...

**Comment by gor181** [comment]
hey @zeroasterisk ,

Thanks for reaching out, will check this one.
Despite the eslint throwing, you are able to use the lib right?

Thanks,

**Comment by gor181** [comment]
+ Are you using https://github.com/benmosher/eslint-plugin-import for `import/named` rule?

**Comment by zeroasterisk** [comment]
1. Yes, it is working correctly, no problems aside from linter.
2. I am using that esling plugin, and it's working correctly for my many other packages and local files

**Comment by jerairrest** [comment]
@zeroasterisk Is this still considered a open issue? Thanks!

**Comment by jerairrest** [comment]
@zeroasterisk for now I'm closing this. Feel free to reopen if the problem persists.

**Comment by zeroasterisk** [comment]
sorry - I wasn't keeping up on emails - I'm not using this project currently so I don't know - therfore closing is fine - thanks!
