### ISSUE TITLE
legendCallback data issue

### ISSUE THREAD

**Issue by seonixx** [gor181/react-chartjs-2#27]
I'm running into a weird issue with setting a custom legend via legendCallback(chart)...

I need to access the chart data and labels to create my custom legend. As far as I can see, this is located in chart.data.labels and chart.data.datasets[0].data.

If I assign/console log chart I can see the data and labels present in the object, however if I try to access chart.data directly, both labels and data are empty arrays. Is there something I'm missing as to why this is the case? I can see there are get and set methods on the prototype of chart.data. Is there something that prevents directly accessing these properties?

**Comment by gor181** [comment]
Hey @seonixx ,

Apologies for late response.
I have just tried to access the data:

![image](https://cloud.githubusercontent.com/assets/8964589/18492587/5b18b662-7a0c-11e6-822a-e6dc71b5b660.png)

Seems fine.

Do you have a code snippet? It would really help.

Thanks

**Comment by gor181** [comment]
@seonixx closing, feel free to reopen if you managed to solve it or if issue still exists.

thank you,

**Comment by majidequbal** [comment]
Hi,

Adding custom legend with callback functions in react but this is not working kindly share solution of this on `urgent` basis. See how i want custom legend [click here](http://neuronimbusinteractive.com/legend.jpg) to see this
