### ISSUE TITLE
Add /src to .npmignore

### ISSUE THREAD

**Issue by patgoley** [gor181/react-chartjs-2#28]
Including uncompiled source is likely to make a lot of build scripts (webpack, etc) fail, as it did for me on first install. Someone installing from npm is likely only interested in the lib folder and not in modifying the source. Consider adding /src to .npmignore so this module can be installed and used easily without having to set up exclusion rules to not bundle the uncompiled source code.

**Comment by gor181** [comment]
Hey @patgoley ,

Thanks for this, makes a lot of sense.
Going to implement shortly.

Goran
