### ISSUE TITLE
I want a new property of onDatasetClick

### ISSUE THREAD

**Issue by ledsun** [gor181/react-chartjs-2#29]
The `onElementsClick` returns ` the element under the event point, then returns all elements at the same data index`.
But I want to know which dataset is clicked. In other words I want to get a dataset that the clicked element in.

So, I want an `onDatasetClick` property that returns `the element under the event point, then returns all elements from that dataset` by the `.getDatasetAtEvent(e)` of the Chart.js instance.

[Reference](http://www.chartjs.org/docs/)

Thank you.

**Comment by gor181** [comment]
Hey @ledsun ,

Apologies for late reply and thanks for reporting.
Will look into it shortly.

Thanks,
Goran

**Comment by ledsun** [comment]
The `.getDatasetAtEvent(e)` is no longer required for me.
Thank you.

**Comment by selimovicz** [comment]
Hi @gor181, is there any way to implement getDatasetAtEvent(event). I need this desperately.
