### ISSUE TITLE
deepEqual implementation issue

### ISSUE THREAD

**Issue by scottwey** [gor181/react-chartjs-2#30]
There is a problem with the implementation of deepEqual.
``deepEqual(["A","B"],["A","B","C"])`` returns true, which it should not.

From my testing, this is a problem because the algorithm only tests if "objA" has properties that "objB" doesn't have and not if "objB" has properties that "objA" doesn't have. So if "objB" is a superset of "objA", deepEqual evaluates correctly.

**Comment by gor181** [comment]
@scottwey thanks for reporting
@brafdlog thanks for fixing it so quickly!
