### ISSUE TITLE
Type definition case problem

### ISSUE THREAD

**Issue by ttamminen** [gor181/react-chartjs-2#33]
[This PR](https://github.com/gor181/react-chartjs-2/commit/220da1ad059b525143e67e3d507f63a85dc808ec) that was merged and released to the version 1.2.7 has type definitions for the react-chartjs-2. Unfortunately, I get an error that module React cannot be found and it seems to be because React starts with an uppercase letter.

When I change the type definition file's first line to this:

```
import * as React from 'react';
```

Everything works correctly.

I am running on Windows system using tsc 1.8.10 and 2.0.3

**Comment by gor181** [comment]
Hey @ttamminen ,

Thanks for reporting it.
Should be fixed in `1.2.8`

Cc @FChapeau 

Thanks,
Goran

**Comment by ttamminen** [comment]
Thank you for the quick reply, great work!
