### ISSUE TITLE
Charts blurry when printed

### ISSUE THREAD

**Issue by wilhen01** [gor181/react-chartjs-2#34]
We're using react-chartjs-2 for a sales reporting application and the users are keen to be able to save the reports as PDF / print them in order to take copies out and discuss them outside the building (it's an intranet app so no external access). We've noticed that the charts render quite blurry when PDF'd or printed to paper.

I found some chat on StackOverflow (e.g. http://stackoverflow.com/questions/34897515/chartjs-jspdf-blurry-image) suggesting that this was down to the canvas size of the chart but I haven't had any luck varying the canvas size using the width/height properties. Any suggestions?

**Comment by gor181** [comment]
Hey @wilhen01 ,

Thanks for reaching out.
Seems that this is really a ChartJS issue people are working around.

Have you tried looking into solutions presented in https://github.com/chartjs/Chart.js/issues/1961
https://github.com/chartjs/Chart.js/issues/99

I hope those will be of help.
Personally I didn't get to the rendering to PDF yet, so cannot speak from my experience.

Maybe someone else who uses the lib did.

Thanks,
Goran

**Comment by wilhen01** [comment]
Hi Goran,

Thanks for the suggestions. I tried some of the settings suggested in those issues but nothing really seems to be helping, and quite a lot of those solutions rely on modifying elements on the page after chart rendering which doesn't really fit with the React way of working. It's only a minor annoyance but it is weird that they display fine on screen and then end up blurry upon PDFing or Printing via Chrome.

Would it be possible to expose something through the component options to allow modifying the canvas size for a chart? I suspect the solution I've seen proposed where you use a higher resolution canvas might fix the printing issues. 

Thanks,
Henry

**Comment by gor181** [comment]
Hey,

I guess we can remove `width` and `height` at https://github.com/gor181/react-chartjs-2/blob/master/src/Chart.js#L62

Would you be able to fork the project and try out?

Cheers,
Goran

**Comment by wilhen01** [comment]
Hi Goran,

I realised that the problem is actually being made way worse by our use of Bootstrap styles which scale the graph containers (and hence ultimately make them smaller). It's not noticeable on screen (even if you zoom in, since this redraws the graphs) but as soon as you print or PDF the browser is kinda snapshotting the images in scaled down form and seems to blur them as a result. Removing the bootstrap styles pretty much sorts this out - I'll need to look at some overrides in a print stylesheet to have the best of both worlds. 

Thanks for your help, and sorry for the slight wild goose chase!

Cheers,
Henry

**Comment by gor181** [comment]
Hey @wilhen01,

So glad that you have sorted it. The issue you have created will certainly be useful to someone with the similar problem 👍
