### ISSUE TITLE
width and height do not work for me

### ISSUE THREAD

**Issue by DimaXu** [gor181/react-chartjs-2#38]
I like this library very much. But in my testing with react-chartjs-2@1.3.0 and chart.js@2.3.0, the width and height do not work for me. 
I set them as 300 and 200 respectively, the result was that the pie and  Doughnut occupied the whole width of the page. I wonder whether something is wrong with my code or anything else in this library. Any response will be appreciated. 

my code is:
    <Pie
        data={this.phyiscalMemory}
        width={300}
        height={200}
        options={{
           maintainAspectRatio: false
         }}
    />
    <Doughnut data={this.virtualMemory} width={250} height={200}/>

![screenshot from 2016-10-05 12 14 19](https://cloud.githubusercontent.com/assets/10850159/19095936/5d02b910-8af5-11e6-93d0-f1f5fadd6571.png)

**Comment by DimaXu** [comment]
It should not be committed as an issue.

**Comment by iarry** [comment]
What was the fix here? I'm having the same issue.

**Comment by gor181** [comment]
hey @iarry 

have you tried https://github.com/gor181/react-chartjs-2#custom-size ?

Cheers,

**Comment by iarry** [comment]
Yep, I set `maintainAspectRatio: false`. I can make the graph grow larger, but it won't go below `497px x 200px`

**Comment by iarry** [comment]
I managed to change the width and height with CSS on the `canvas`, but it needed `!important` tags.

**Comment by alexis-thual** [comment]
This still is an ongoing issue for me.
I used `maintainAspectRatio: false` in the options while trying to specify the `height` and `width` of a `Line` chart. The height works correctly but the width won't change. I had to put this `Line` in a `div` that has the appropriate width.
```return (
            <div style={{width: '200px'}}>
                <Line
                    data={data}
                    options={options}
                    height={200}
                    width={400}
                />
            </div>
        )```

**Comment by huyvohcmc** [comment]
Did anybody find a way to fix this issue?

**Comment by solaomosola** [comment]
I have the same issue.

**Comment by MikeRoberts2008** [comment]
I'm having this same issue, the height is respected but the width is ignored:

`<Line data={data} width={200} height={200}  options={{ maintainAspectRatio: false }} />`

**Comment by nhuthan** [comment]
I have same issue, using doughnut

**Comment by KennethChiu123** [comment]
try
<Line data={data} width={200} height={200} options={{ maintainAspectRatio: false ,responsive:false }} />

**Comment by jayaramsurya** [comment]
when i decrease the width the screen , the graph width can't change but height will change . I tired many solution nothing works

**Comment by jayaramsurya** [comment]
when i decrease the width the screen , the graph width can't change but height will change . I tired many solution nothing works

**Comment by DPTeamMember** [comment]
@KennethChiu123 

<Line data={data} width={200} height={200} options={{ maintainAspectRatio: false }} />
This worked for me.` responsive:false` was not necessary for me.

Thank you.

**Comment by alex-drocks** [comment]
> data={data} width={200} height={200} options={{ maintainAspectRatio: false ,responsive:false }}

Only this solution worked for me.

**Comment by shubhamsharma2k** [comment]
This is the solution https://react-chartjs-2.js.org/faq/maintain-aspect-ratio/
