### ISSUE TITLE
you forgot to update builds for version > 1.2.6

### ISSUE THREAD

**Issue by zetta83** [gor181/react-chartjs-2#42]
https://github.com/gor181/react-chartjs-2/commit/7a36b848a408ce07f2d29181600c2b73975ad754 - these changes will have no effect if installed via npm

**Comment by gor181** [comment]
hey @zetta83 ,

Whole `src` folder is ignored by npm.
Those files are used only in dev mode.

Maybe I'm missing a point.

Thanks,

**Comment by gor181** [comment]
Hey @zetta83 ,

Closing , please reopen if needed.

thanks
