### ISSUE TITLE
Window is undefined

### ISSUE THREAD

**Issue by mira-thakkar** [gor181/react-chartjs-2#43]
In my isomorphic app, i have installed react-chartjs-2 and chart.js. 
I am using line chart for displaying charts.

```
import React,{Component} from 'react'
import {Line} from 'react-chartjs-2'

const data = {
  labels: ['January','','February', '','March'],
  datasets: [
    {
      label: 'Last 24 hours data',
      fill: true,
      backgroundColor: 'rgba(88,96,103,0.6)',
      borderColor: 'rgba(75,192,192,1)',
      borderCapStyle: 'butt',
      borderDash: [],
      borderDashOffset: 0.0,
      borderJoinStyle: 'miter',
      pointBorderColor: 'rgba(75,192,192,1)',
      pointBackgroundColor: '#fff',
      pointBorderWidth: 1,
      pointHoverRadius: 5,
      pointHoverBackgroundColor: 'rgba(75,192,192,1)',
      pointHoverBorderColor: 'rgba(220,220,220,1)',
      pointHoverBorderWidth: 2,
      pointRadius: 1,
      pointHitRadius: 10,
      data: [65, 59, 80, 81, 56, 55, 40]
    }
  ]
};

const options = {
  scales: {
    xAxes: [{
      display: true,
      gridLines : {
        color: "#464f56",
        lineWidth: 0,
        showTickMarks: false
      },
      ticks: {
        beginAtZero:true,
      },

    }],
    yAxes:[{
      gridLines: {
        lineWidth: 1,
        color: "#fff",
      },
      ticks: {
        stepSize:40,
        beginAtZero:true,
        showLabelBackdrop: true
      },

    }]
  },
  scaleStartValue: 0,
  maintainAspectRatio: true
};

export default class Test extends Component{
        render(){
               return (
                     <div>
                         {
                          window != undefined
                          ?
                          <Line data={data} options={options} />
                          :
                         null
                         }
                     </div>
               )
        }
}
```
But when i run the app using npm start, I am getting following error:

```
           return window.requestAnimationFrame ||
                       ^
ReferenceError: window is not defined
    at /myapp/node_modules/chart.js/src/core/core.helpers.js:676:10
```
Any ideas as to the cause or how to fix it?
Thanks.

**Comment by gor181** [comment]
Hey @mira-thakkar,

Thanks for reaching out.

When doing server rendering there is no `window` available thus you are unable to render them server side.

The error you are getting is directly from the chart.js library, unfortunately as per my knowledge there isn't much we can do..

**Comment by gor181** [comment]
If you manage to find a workaround please do post it to this issue so other people will be able to reference it.

Closing till then.
Thank you for reporting.

**Comment by nevace** [comment]
This is horrible but it works.. https://github.com/reactjs/react-chartjs/issues/57

**Comment by danieljames-dj** [comment]
This error is happening for my next.js application, did anybody got a solution for this?

**Comment by tbvjwodn2** [comment]
same here, my next.js complains about this

**Comment by Oceanestars** [comment]
@tbvjwodn2 What fixed it for me in NextJS at least(So maybe even if you don't use NextJS some stuff on that page can be useful) is I had to import the parent component that contained the chart [dynamically](https://nextjs.org/docs/advanced-features/dynamic-import)

```
import dynamic from 'next/dynamic'

const SidePanel = dynamic(() => import('./components/sidePanel'), { ssr: false });

```

That side panel component has my line chart chart from reach chart.

**Comment by tbvjwodn2** [comment]
> @tbvjwodn2 What fixed it for me in NextJS at least(So maybe even if you don't use NextJS some stuff on that page can be useful) is I had to import the parent component that contained the chart [dynamically](https://nextjs.org/docs/advanced-features/dynamic-import)
> 
> ```
> import dynamic from 'next/dynamic'
> 
> const SidePanel = dynamic(() => import('./components/sidePanel'), { ssr: false });
> ```
> 
> That side panel component has my line chart chart from reach chart.

Thank you for the help! :)

**Comment by yashwason** [comment]
> @tbvjwodn2 What fixed it for me in NextJS at least(So maybe even if you don't use NextJS some stuff on that page can be useful) is I had to import the parent component that contained the chart [dynamically](https://nextjs.org/docs/advanced-features/dynamic-import)
> 
> ```
> import dynamic from 'next/dynamic'
> 
> const SidePanel = dynamic(() => import('./components/sidePanel'), { ssr: false });
> ```
> 
> That side panel component has my line chart chart from reach chart.

This works perfectly!
