### ISSUE TITLE
Option to register a plugin

### ISSUE THREAD

**Issue by awahlfischle** [gor181/react-chartjs-2#45]
Is there a possibility to use the Chart.pluginService.register-functionality ?

http://www.chartjs.org/docs/#advanced-usage-creating-plugins

Stumpled upon this as a solution for a lot of things, but don't see an option to use it with this component right now. Maybe I miss something ?

**Comment by gor181** [comment]
Hello @awahlfischle ,

Apologies for late reply.

What comes to my mind is that we can export `plugins` so you can have access to `register` method.

So in the end you would have 1 file which requires the `react-chartjs-2` registers the plugins.
I think it should work just fine.

Let me know whether this approach is fine with you so we can continue onto this.

Thanks,
