### ISSUE TITLE
React 15 support?

### ISSUE THREAD

**Issue by kibin** [gor181/react-chartjs-2#5]
Is this library specifically for react 0.14?

**Comment by jensamunch** [comment]
seems to works fine for react 0.15...maybe somebody could change this dependency?

**Comment by kibin** [comment]
I didn’t use it in the end because I needed to support server side rendering. I think anyone can do a PR, but there are no tests in the sources of this lib, so it’s somewhat risky.

**Comment by gor181** [comment]
Hello,

Apologies for late replies... Should work with React 15 without any warnings now.
Released 1.1.5.

Sorry for no tests yet.
Any PR's are always welcome, thanks.

Closed via e9179
Cheers.
