### ISSUE TITLE
Component completely fails in Windows environment

### ISSUE THREAD

**Issue by mosanger** [gor181/react-chartjs-2#52]
Running and bundling spits out the following errors:

> WARNING in ./~/react-chartjs-2/lib/Chart.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

> WARNING in ./~/react-chartjs-2/lib/chart.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

So as Windows doesn't support case sensitive filenames, `require('chart.js')` does not know which file to include here. Chart.js or chart.js

I managed to fix this by simply renaming `/lib/Chart.js` to `/lib/index.js` while also adjusting the main entry in package.json.

I can make a pull request if you want me to.

**Comment by gor181** [comment]
hey @mosanger ,

thanks for reporting.
If you have time PR would be awesome as I'm currently unable to :(
