### ISSUE TITLE
Any examples for legend?

### ISSUE THREAD

**Issue by sailhenz** [gor181/react-chartjs-2#56]
Hi, 

Any examples for legend?
I tried something like:

`        <Doughnut
          data={this.props.doughnutData}
          legend={{display: true,position: 'bottom'}}
        />
`

but the legend is still on top of the chart.

Thank you in advance.

**Comment by sailhenz** [comment]
I figured it out. 
Need to put it in options.

**Comment by gmkhussain** [comment]
Pass an **options** object in chart return structure

See code example:
```javascript
// . . .
render() {
  const options = {
        legend: {
            display: true,
            position: 'left'
        },
  };
    return (
      <div>
        <Line data={this.state.chartData} height="50" options={options} />
      </div>
    )
  }
//  . . .
```
