### ISSUE TITLE
Static Label in Pie Chart and Doughnut Chart

### ISSUE THREAD

**Issue by sailhenz** [gor181/react-chartjs-2#58]
Is it possible to put a responsive label in the chart itself instead of tooltip?

**Comment by jerairrest** [comment]
Is that functionality available in chartjs?

**Comment by jerairrest** [comment]
@sailhenz I'm closing this for now. If you come back with an example of what you would like I would be more than happy to help.

**Comment by eswat2** [comment]
i believe this is possible by registering a plugin with Charts.js. You can see how i did this in a jsfiddle using just Charts.js here -- https://jsfiddle.net/eswat2/hpemakk7/12/

That renders a concentric set of doughnuts and then renders a number in the middle.

I was able to do much the same thing using react-chartjs-2
