### ISSUE TITLE
Shallow props comparison in shouldComponentUpdate() makes charts redraw too frequently

### ISSUE THREAD

**Issue by leifkb** [gor181/react-chartjs-2#6]
The intention of the code seems to be that it will only redraw when the props are actually different, but in practice, it redraws as long as the props are a different object (i.e. basically always).

**Comment by gor181** [comment]
Hey @leifkb,

Apologies for late reply.
You are correct, we should either do deep comparison (somewhat performance ineffective) or we can return false for shouldComponentUpdate and if "redraw" is true in componentWillReceiveProps force an update?

Any thoughts are welcome.

Thanks for your time.
