### ISSUE TITLE
Reload on height and width changes

### ISSUE THREAD

**Issue by volkandkaya** [gor181/react-chartjs-2#60]
I am trying to reload if height and width change. I can't find any methods to do that. 

Are there any plans to add this functionality?

**Comment by gor181** [comment]
hey @volkandkaya ,

I have #59 open which should include that possibility too, needs a bit fine tuning and then it's ready to go.

**Comment by volkandkaya** [comment]
@gor181 how long until it will be ready for use? This package is perfect except for the reloading.

**Comment by gor181** [comment]
hey @volkandkaya ,

I have an issue with getting tests to pass on Travis, while working nicely locally..
So besides that there are no issues on merging it in.

I need to think whether I can skip that test stuff for now.
Will let you know shortly.

**Comment by gor181** [comment]
hey @volkandkaya ,

`1.6.0` has been released.

Basically all you need is to modify the `width` or / and `height` props.
let me know how it goes.

**Comment by volkandkaya** [comment]
Thanks, I can't get it working. It refreshes but the height and width don't change. 

However I was also changing the colours and that didn't work, after 1.6 it now works which is great. So I am not sure why height and width don't work.

**Comment by gor181** [comment]
hey,

I would suggest to add the div with style (width, height) around as we render only `canvas` element which width/height seems to be overriden by chart.js regardless of what options are set.

**Comment by volkandkaya** [comment]
Is there anyway to force a refresh, if I switch using react-router it fixes itself. So I need to unmount and mount I guess.

**Comment by gor181** [comment]
Tried `redraw={true}` ?

**Comment by volkandkaya** [comment]
Didn't work. I will stick to key for now. Thanks for all the help.

**Comment by janpaul123** [comment]
This is still a problem for me. I also ended up using
```js
key={`${width}x${height}`}
```
