### ISSUE TITLE
Remove border

### ISSUE THREAD

**Issue by n1c01a5** [gor181/react-chartjs-2#69]
I will remove border around the doughnut graph.

Is-it possible ?

**Comment by jerairrest** [comment]
Do you mean the white border between the segments? Or the border around?

**Comment by n1c01a5** [comment]
@jerairrest the border around

**Comment by jerairrest** [comment]
Hey @n1c01a5 

please use the follow option object to remove the border.

```
const options = {
	elements: {
		arc: {
			borderWidth: 0
		}
	}
}
```

**Comment by shivbasav** [comment]
@jerairrest I tried with your option object doesn't seem to work for me
