### ISSUE TITLE
Feature Request: Allow style prop to be passed

### ISSUE THREAD

**Issue by volkandkaya** [gor181/react-chartjs-2#75]
Would be great to pass style like {marginLeft: 'auto', marginRight: 'auto'}, that would centre the canvas without needing to create a div around it.

**Comment by gor181** [comment]
Hey @volkandkaya ,

Style is actually replaced by chart.js so not sure whether we can do much.
Solution would be to wrap the chart in a div and set the styles there.

**Comment by volkandkaya** [comment]
Oh okay. Yeah that is fine then I can just do it my end, no point bloating the props.
