### ISSUE TITLE
dist/react-chartjs-2.js throws "Uncaught Error: Cannot find module 'react-dom'", latest versions of everything

### ISSUE THREAD

**Issue by jeffvandyke** [gor181/react-chartjs-2#78]
I'm trying to get this to work with an existing project, and am using the latest version of react-with-addons/react-dom, 15.4.1 via CDN, and the latest version of Chart.js as well. I'm not familiar enough with the UMD way of doing modules to fix it, and we can't really use browserify or webpack in our current environment.

Currently, the project "react-chartjs" branch "chartjs-v2" works with the latest version of everything, so I'm using that for now, but let me know if you need anything from me for this issue.

**Comment by jerairrest** [comment]
Hey Jeff!

Thanks for reporting this. Do you have a quick example of how you're currently setting up your page? I'd love to see an example that's causing this issue.

**Comment by jeffvandyke** [comment]
I've just uploaded a mockup project that has the bare minimum (I believe) to reproduce this error. Instructions are in /README.md.

Let me know if you need any other information; README.md should be pretty self-explanitory.

[problem-mockup.zip](https://github.com/gor181/react-chartjs-2/files/647132/problem-mockup.zip)

**Comment by jerairrest** [comment]
Thanks for the example! This project currently uses browserify to do it's bundling which I'm unfamiliar with so it may take a bit of work to debug. I'll let you know what I find.

Cheers!

Jer

**Comment by jerairrest** [comment]
Hey @jeffvandyke can you please test the dist file found in https://github.com/gor181/react-chartjs-2/pull/82 ?

Note: instead of using window['react-chartjs-2'] use window.reactChartjs2

**Comment by jerairrest** [comment]
Let me know if it doesn't work. Thanks!

**Comment by jeffvandyke** [comment]
Can confirm that this works, excellent! Thanks.
