### ISSUE TITLE
Doesn't update all options

### ISSUE THREAD

**Issue by andylhansen** [gor181/react-chartjs-2#8]
It looks like updates do not actually update all the options for a chart.

In the updateChart method of ChartComponent, it only updates the xAxis and the background colors. Couldn't we simply replace the entire options object with the updated one?

So in the updateChart method you'd put something like this:
`var helpers = Chart.helpers;`
`this.chart_instance.options = helpers.configMerge(this.chart_instance.options, options);`

I discovered this because it throws an error when it tries to update doughnut charts, because they don't have scales.
Could we get this fixed so that it updates all the chart options?

**Comment by gor181** [comment]
Hey @andylhansen ,

thanks for reporting, checking it out

**Comment by gor181** [comment]
Hey @andylhansen,

Thanks for reporting once again, I have just published v1.1.7 which fixes that issue (394870617559cd21919dc21269b9f758143d93f5) and adds a DynamicDougnut Example to examples.

cc @mattandwhatnot

Thank you,
