### ISSUE TITLE
Options aren't applied correctly and tooltips don't appear

### ISSUE THREAD

**Issue by ezhlobo** [gor181/react-chartjs-2#80]
Hi. I was working with 1.5.1. Today I updated dependencies and now paddings for layout aren't applied.

Also tooltips are disappeared.

Here is my options:

```js
    tooltips: {
      enabled: true,
      mode: 'x',
      callbacks: {
        title: (items, data) => data.xLabels[items[0].index],
        label: (item, data) => {
          const dataset = data.datasets[item.datasetIndex];
          const value = dataset.data[item.index];
          const formattedValue = helpers.convertNumberToWord(value);

          return `${dataset.label} — ${formattedValue}`;
        },
      },
    },
    layout: {
      padding: {
        left: 0,
        right: 0,
        top: 15,
        bottom: 0,
      },
    },
```

I'm sure that it's easy to reproduce but let me know if you need more detailed explanation or specific example with my chart.

Temporary I use 1.5.1 because it works well.

Thank you!

**Comment by jerairrest** [comment]
Hey @ezhlobo this may have to do with https://github.com/gor181/react-chartjs-2/issues/40. I'll have to investigate further

**Comment by jerairrest** [comment]
@ezhlobo please see my comment in https://github.com/gor181/react-chartjs-2/issues/84

**Comment by jerairrest** [comment]
Hey @ezhlobo this looks like this was resolved in v2. Let me know if you have anymore troubles

**Comment by ardsouza** [comment]
@jerairrest layout does not work for me in v2
