### ISSUE TITLE
How to not show legend?

### ISSUE THREAD

**Issue by witalobenicio** [gor181/react-chartjs-2#86]
I want to use a pie chart but without labels (legend). It is possible?

**Comment by roboslone** [comment]
@limiterCore , this doesn't work for me on `react-chartjs-2@1.6.2`, is there any other way?

**Comment by limiterCore** [comment]
@roboslone I can't see any legend on your chart, therefore it works. If you are about scales labels, please add this to the options object:

`scales: {
	xAxes: [{
		display: false,
	}],
	yAxes: [{
		display: false,
	}],
},`

**Comment by roboslone** [comment]
@limiterCore , sorry, you're right. Thanks!

**Comment by justkapoor** [comment]
@limiterCore , Hey I want to show label on my X-axis and Y-axis and also want to have prefix when we hover the point.
Can you please help me in that?

**Comment by AnubhavJohri** [comment]
How to hide one particular legend while using legend : { display : false}

**Comment by BasitMaqsood** [comment]
> @roboslone I can't see any legend on your chart, therefore it works. If you are about scales labels, please add this to the options object:
> 
> `scales: { xAxes: [{ display: false, }], yAxes: [{ display: false, }], },`

Thanks, it's really Helpful

**Comment by pelleknaap** [comment]
The legend setting is now embedded inside the plugins object like this with Chart.js V3:
```
    plugins: {
        legend: {
            display: false,
        },
    }
```

For future reference if people come across this issue via Google, want to save them some time

**Comment by mike392** [comment]
> The legend setting is now embedded inside the plugins object like this with Chart.js V3:
> 
> ```
>     plugins: {
>         legend: {
>             display: false,
>         },
>     }
> ```
> 
> For future reference if people come across this issue via Google, want to save them some time

Only this worked for me - without using ```plugin``` in versions of react-chartJS 3+ it's useless

**Comment by dcastrocoder** [comment]
To hide leyend apply: 
`import React from "react";
import { Doughnut } from "react-chartjs-2";
const options = {  // config options
  plugins: {
    legend: {
      display: false,
    },
  },
};
const data = {
  labels: ["Red", "Blue"],
  datasets: [
    {
      label: "# of Votes",
      data: [80, 20],
      backgroundColor: ["rgba(255, 99, 132, 0.2)", "rgba(54, 162, 235, 0.2)"],
      borderColor: ["rgba(255, 99, 132, 1)", "rgba(54, 162, 235, 1)"],
      borderWidth: 0,
    },
  ],
};
const ProfileCard = () => {
  return (
<div>
 <Doughnut data={data} options={options} />  // props to hide labels
</div>
);
};`

**Comment by znwhite** [comment]
> To hide leyend apply:
> 
> ` import React from "react";
> import { Doughnut } from "react-chartjs-2";
> const options = { // config options <<<<<<<<---------
> plugins: {
> legend: {
> display: false,
> },
> },
> };
> const data = {
> labels: ["Red", "Blue"],
> datasets: [
> {
> label: "# of Votes",
> data: [80, 20],
> backgroundColor: ["rgba(255, 99, 132, 0.2)", "rgba(54, 162, 235, 0.2)"],
> borderColor: ["rgba(255, 99, 132, 1)", "rgba(54, 162, 235, 1)"],
> borderWidth: 0,
> },
> ],
> };
> const ProfileCard = () => {
> return (
> 
> // props to hide labels <<<<<----------
> ); }; `

Thanks! Making sure I wrapped the `legend` option in `plugins` fixed it for me.

ie

```
  const data = {...}
  const options = {
    plugins: {
      legend: {
        display: false
      },
    }
  }

<Line data={data} options={options} />
```

**Comment by M-Rb3** [comment]
> dcastrocoder

finally, it works

**Comment by M-Rb3** [comment]
> To hide leyend apply:
> 
> ` import React from "react"; import { Doughnut } from "react-chartjs-2"; const options = { // config options <<<<<<<<--------- plugins: { legend: { display: false, }, }, }; const data = { labels: ["Red", "Blue"], datasets: [ { label: "# of Votes", data: [80, 20], backgroundColor: ["rgba(255, 99, 132, 0.2)", "rgba(54, 162, 235, 0.2)"], borderColor: ["rgba(255, 99, 132, 1)", "rgba(54, 162, 235, 1)"], borderWidth: 0, }, ], }; const ProfileCard = () => { return (
> 
> // props to hide labels <<<<<----------
> ); }; `

thanks, finally it worked

**Comment by jdsamar** [comment]
> > To hide leyend apply:
> > ` import React from "react";
> > import { Doughnut } from "react-chartjs-2";
> > const options = { // config options <<<<<<<<---------
> > plugins: {
> > legend: {
> > display: false,
> > },
> > },
> > };
> > const data = {
> > labels: ["Red", "Blue"],
> > datasets: [
> > {
> > label: "# of Votes",
> > data: [80, 20],
> > backgroundColor: ["rgba(255, 99, 132, 0.2)", "rgba(54, 162, 235, 0.2)"],
> > borderColor: ["rgba(255, 99, 132, 1)", "rgba(54, 162, 235, 1)"],
> > borderWidth: 0,
> > },
> > ],
> > };
> > const ProfileCard = () => {
> > return (
> > // props to hide labels <<<<<----------
> > ); }; `
> 
> Thanks! Making sure I wrapped the `legend` option in `plugins` fixed it for me.
> 
> ie
> 
> ```
>   const data = {...}
>   const options = {
>     plugins: {
>       legend: {
>         display: false
>       },
>     }
>   }
> 
> <Line data={data} options={options} />
> ```

Thnxs @znwhite this helped
