### ISSUE TITLE
Cannot read property of 'x-axis' of undefined

### ISSUE THREAD

**Issue by mattandwhatnot** [gor181/react-chartjs-2#9]
I'm getting this error "Cannot read property of 'x-axis' of undefined" in the console when ever i try to update the data the chart is using (with tracker react). It looks like it wants the scales defined but its a Pie, there is no scale. (beside the default arc)?? I am using the latest Chartjs 2.1.6, I suspect maybe that is the problem but really I'm at a loss. Whats the last version of Chartjs that was functional with react-chartjs-2??

**Comment by gor181** [comment]
Hello @mattandwhatnot ,

This is the same issue as in #8 
Until fixed you can use version 1.1.5 by doing `npm install react-chartjs-2@1.1.5`

Thank you for reporting
