### ISSUE TITLE
[question] Example for Events provided in docs?

### ISSUE THREAD

**Issue by nealoke** [gor181/react-chartjs-2#91]
I'm not sure how I need to use the events specified in the docs like `getElementsAtEvent`. Are there any examples on this? Or can you provide one?

**Comment by cheong12001** [comment]
i would like to know more too

**Comment by gor181** [comment]
Hello,

Example would be similar to [Bar example](https://github.com/gor181/react-chartjs-2/blob/master/example/src/components/bar.js#L27) just you would add:

`getElementsAtEvent: (elems) => {}`

To the list of defined properties for the `Bar` component, so it would look like:

```
<Bar
  data={data}
  width={100}
  height={50}
  getElementsAtEvent={(elems) => {
    console.log(elems);
  }}
  options={{
    maintainAspectRatio: false
  }}
/>
```

Kr,

**Comment by nealoke** [comment]
@gor181 and what is the event that triggers it? I mean is it when the chart changes or you click on the chart or ... ?

**Comment by jerairrest** [comment]
As seen in this jsfiddle, (not rcjs2 but shows chart.js functionality) https://jsfiddle.net/f417uxcx/ it shows that this function is called from a user clicking on an active point. Hope this helps!

**Comment by nealoke** [comment]
@jerairrest Yes it does thanks!
