### ISSUE TITLE
Support Scatter chart type

### ISSUE THREAD

**Issue by krzema12** [gor181/react-chartjs-2#94]
Chart types supported by react-chartjs-2:
* Bar
* Bubble
* Doughnut
* Line
* Pie
* HorizontalBar
* Radar
* Polar

Chart types supported by chart.js:
* Bar
* Bubble
* Doughnut
* Line
* PolarArea
* Radar
* **Scatter - not supported**

**Comment by jerairrest** [comment]
Minus some styling, it looks like you can use the Line component to create this

import React from 'react';
import {Line} from 'react-chartjs-2';

const data = {
	datasets: [{
		label: 'Scatter Dataset',
		data: [{
			x: -10,
			y: 0
		}, {
			x: 0,
			y: 10
		}, {
			x: 10,
			y: 5
		},
			{
				x: 1,
				y: 5
			}
		]
	}
	],

};

const options = {

		scales: {
			xAxes: [{
				type: 'linear',
				position: 'bottom'
			}]
		}

}

export default React.createClass({
	displayName: 'LineExample',

	render() {
		return (
			<div>
				<h2>Line Example</h2>
				<Line data={data} options={options} />
			</div>
		);
	}
});
