### ISSUE TITLE
Chart JS do not display in IE

### ISSUE THREAD

**Issue by haidermahmood** [gor181/react-chartjs-2#97]
Dear Goran,

Your react component for Chart JS v2 is great. However, I am facing the following issue while running your examples and also using your component in code:
You have used es6 methods like .assign() which does not work on IE unless you have added es6-polyfill. Kindly look into it.  

Regards,
Haider

**Comment by jerairrest** [comment]
Hey there, are you referring to the umd version or the actual npm module? It looks like the npm module has a polyfill for assign it in. https://github.com/gor181/react-chartjs-2/blob/master/lib/index.js#L8

**Comment by haidermahmood** [comment]
Hey @jerairrest if you open exam in IE 11,  you would see the error in the following lines in index.js. https://github.com/gor181/react-chartjs-2/blob/master/lib/index.js#L147
If you remove that and use return JSON.parse(JSON.stringify( set  )), it would work fine in IE.

**Comment by haidermahmood** [comment]
@gor181  do you have the idea regarding it?

**Comment by jerairrest** [comment]
I have opened up a PR that would solve there. https://github.com/gor181/react-chartjs-2/pull/103 Can you verify?

**Comment by jerairrest** [comment]
This is fixed in 2.0.4. Enjoy!
